### ISSUE TITLE
Soft Links

### ISSUE THREAD

**Issue by soehlert** [shyiko/dotfiles#1]
I noticed you have to set up lots of soft links with your dotfiles repo. Just a hint that may help. Gnu Stow is great at dealing with this exact thing. A couple of blogs dealing with it. 

http://blog.samoehlert.com/gnu-stow (full disclosure, this one's mine)
http://taihen.org/managing-dotfiles-with-gnu-stow/

**Comment by shyiko** [comment]
Nice! Thanks, man.
